name:                prototypes
version:             0.1.0.0
homepage:            https://github.com/ddrone/language
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - text

ghc-options:
  - -fwrite-ide-info
  - -hiedir=hie

executables:
  prototypes:
    source-dirs:      src
    main:             Main.hs
